	git rm bloque_genera_pilots.vhd
	git rm bloque_genera_symbOFDM.vhd
	git rm bloque_genera_symbs_and_pilots_tb.vhd
	git rm cont_21.vhd
	git rm div12_signed.vhd
	git rm div12_signed_tb.vhd
	git rm div12_tb.vhd
	git rm divider12.vhd
	git rm divider12_tb.vhd
	git rm divider_precise.vhd
	git rm divider_usigned.vhd
	git rm divider_usigned_tb.vhd
	git rm ipcore_dir/coregen.log
	git rm ipcore_dir/tmp/_xmsgs/netgen.xmsgs
	git rm ipcore_dir/tmp/_xmsgs/ngcbuild.xmsgs
	git rm ipcore_dir/tmp/_xmsgs/pn_parser.xmsgs
	git rm ipcore_dir/tmp/_xmsgs/xst.xmsgs
	git rm tb_bloque_2.vhd
	git rm tb_bloque_3.vhd
	git rm tb_bloque_4.vhd
	git rm tb_bloque_7.vhd
	git rm tb_bloque_genera_pilots.vhd
	git rm tb_bloque_genera_symbOFDM.vhd
	git rm tb_bloques_23.vhd
	git rm tb_bloques_234.vhd
	git rm tb_clk_datagen.vhd
	git rm tb_cont_0_12_1704.vhd
	git rm tb_multcomplex_12.vhd
	git rm twos_compliment_tb.vhd
	git rm verification/bloque_14_ch_est.txt
	git rm verification/bloque_2_rx_symb.txt
	git rm verification/bloque_3_rx_symb.txt
	git rm verification/bloque_5_prbs.txt
	git rm verification/bloque_8_rx_pilots.txt
	git rm verification/bloque_8_tx_pilots.txt
	git rm verification/bloque_9_pilots_est.txt
	git rm verification/matlab_H_est.txt
	git rm verification/matlab_H_est_interp.txt
	git rm verification/matlab_files
	git rm verification/matlab_interpoled_data.txt
	git rm verification/matlab_pilots_est.txt
	git rm verification/matlab_prbs.txt
	git rm verification/matlab_rx_pilots.txt
	git rm verification/matlab_symbOFDM.txt
	git rm verification/matlab_tx_pilots.txt
	git rm verification/tb_interpoled_data.txt
	git rm verification/update_matlab_data.sh
	git rm verification/verify.sh

